### PR TITLE
Unbreak the build: use std::isfinite

### LINKED ISSUE #17: error: 'isfinite' was not declared in this scope; did you mean 'std::isfinite'?
```
cum_median.cpp: In function 'int cum_median(int, double*, double*, double*)':
cum_median.cpp:10:9: error: 'isfinite' was not declared in this scope; did you mean 'std::isfinite'?
   10 |     if(!isfinite(data_value)){
      |         ^~~~~~~~
      |         std::isfinite
In file included from /opt/local/include/LegacySupport/cmath:54,
                 from PiecewiseFunction.h:16,
                 from cum_median.cpp:3:
/opt/local/include/gcc12/c++/cmath:578:5: note: 'std::isfinite' declared here
  578 |     isfinite(_Tp __x)
      |     ^~~~~~~~
make: *** [cum_median.o] Error 1
```

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://github.com/tdhock/binsegRcpp/issues/17

### CODE REVIEW

**Comment by barracuda156** [comment]
CI failures unrelated to the PR.

**Comment by tdhock** [comment]
hi thanks for the PR! can you please clarify what build this would fix? I do not see the warning in that linked issue in any builds.

**Comment by barracuda156** [comment]
@tdhock Relevant for older macOS; analogous to `isnan` issue here, for example: https://github.com/AcademySoftwareFoundation/openexr/pull/1448

AFAIK, this should not have any adverse affects for other systems; of course, if any such concerns exist, the fix should be conditional.

**Comment by barracuda156** [comment]
P. S. On macOS this is confirmed to build fine across every system from 10.6 through 13: https://ports.macports.org/port/R-binsegRcpp/details
PowerPC build confirmed locally (no buildbot for it at the moment).
We apply the fix unconditionally, so it works both with Clang and GCC: https://github.com/macports/macports-ports/blob/master/R/R-binsegRcpp/Portfile

**Comment by barracuda156** [comment]
@tdhock Thanks for merging!

**Pull request merged**
